apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gardener-extension-dummy-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-dummy-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-dummy-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  unhealthyPodEvictionPolicy: AlwaysAllow
