---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-dummy-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-dummy-service
    helm.sh/chart: gardener-extension-dummy-service
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
